export const FILTER_SITEID_CHANGED = "FILTER_SITEID_CHANGED";
export const FILTER_SITENAME_CHANGED = "FILTER_SITENAME_CHANGED";
export const FILTER_SITETAXID_CHANGED = "FILTER_SITETAXID_CHANGED";
export const FILTER_SITERECEIVERID_CHANGED = "FILTER_SITERECEIVERID_CHANGED";

export const REQUEST_SITES = "REQUEST_SITES";
export const RECEIVE_SITES = "RECEIVE_SITES";
export const SITE_SELECTED = "SITE_SELECTED";
export const FETCH_SITES = "FETCH_SITES";
export const CONFIG_EDIT = "CONFIG_EDIT";
export const CONFIG_VIEW = "CONFIG_VIEW";
export const CONFIG_DUPLICATE = "CONFIG_DUPLICATE";
export const CONFIG_DELETE = "CONFIG_DELETE";
export const CONFIG_NEW = "CONFIG_NEW";
export const FETCH_CONFIGS = "FETCH_CONFIGS";

export const SITE_DETAIL_VIEW = "SITE_DETAIL_VIEW";
export const SITE_LIST_VIEW = "SITE_LIST_VIEW";
export const SITE_TEMPLATES_VIEW = "SITE_TEMPLATES_VIEW";
export const SITE_NEW_VIEW = "SITE_NEW_VIEW";
export const SITE_DUPL_VIEW = "SITE_DUPL_VIEW";
export const SITE_GPARAMS_LIBRARY_VIEW = "SITE_GPARAMS_LIBRARY_VIEW";

export const CONFIG_LIST_VIEW = "CONFIG_LIST_VIEW";
export const CONFIG_DETAIL_VIEW = "CONFIG_DETAIL_VIEW";
export const CONFIG_EDIT_VIEW = "CONFIG_EDIT_VIEW";

export const PARAM_SELECTED = "PARAM_SELECTED";
export const GET_PARAM_INFO = "GET_PARAM_INFO";
export const OPEN_EDIT_PARAM_MODAL = "OPEN_EDIT_PARAM_MODAL";
export const CLOSE_EDIT_PARAM_MODAL = "CLOSE_EDIT_PARAM_MODAL";
export const CHANGE_ACTIVE_PARAM_OPTION = "CHANGE_ACTIVE_PARAM_OPTION";
export const UPDATE_ACTIVE_CONFIG = "UPDATE_ACTIVE_CONFIG";
export const CHANGE_ACTIVECONFIG_RECEIVERID = "CHANGE_ACTIVECONFIG_RECEIVERID";
export const CHANGE_ACTIVECONFIG_USAGE = "CHANGE_ACTIVECONFIG_USAGE";
export const CHANGE_ACTIVECONFIG_PURPOSE = "CHANGE_ACTIVECONFIG_PURPOSE";
export const CHANGE_ACTIVECONFIG_FLDSEP = "CHANGE_ACTIVECONFIG_FLDSEP";
export const REQUEST_CONFIG_DETAIL = "REQUEST_CONFIG_DETAIL";
export const RECEIVED_CONFIG_DETAIL = "RECEIVED_CONFIG_DETAIL";
export const REQUEST_UPDATE_CONFIG = "REQUEST_UPDATE_CONFIG";
export const COMPLETED_UPDATE_CONFIG = "COMPLETED_UPDATE_CONFIG";

export const OPEN_ADD_PARAM_MODAL = "OPEN_ADD_PARAM_MODAL";
export const CLOSE_ADD_PARAM_MODAL = "CLOSE_ADD_PARAM_MODAL";
export const ADD_PARAM_MODAL_FILTER_CHANGED = "ADD_PARAM_MODAL_FILTER_CHANGED";
export const ADDPARAM_FORMCONTROL_SELECTED = "ADDPARAM_FORMCONTROL_SELECTED";
export const ADDPARAM_SET_VALUE = "ADDPARAM_SET_VALUE";
export const REQUEST_PARAMS = "REQUEST_PARAMS";
export const RECEIVE_PARAMS = "RECEIVE_PARAMS";
export const UPDATE_PARAMS = "UPDATE_PARAMS";

export const OPEN_CONFIRMATION_MODAL = "OPEN_CONFIRMATION_MODAL";
export const CLOSE_CONFIRMATION_MODAL = "CLOSE_CONFIRMATION_MODAL";
export const UPDATE_CONFIG_FAILED = "UPDATE_CONFIG_FAILED";

export const OPEN_NEWCONFIG_MODAL = "OPEN_NEWCONFIG_MODAL";
export const CLOSE_NEWCONFIG_MODAL = "CLOSE_NEWCONFIG_MODAL";
export const UPDATE_NEWCONFIG_RECEIVERID = "UPDATE_NEWCONFIG_RECEIVERID";
export const UPDATE_NEWCONFIG_PURPOSE = "UPDATE_NEWCONFIG_PURPOSE";
export const UPDATE_NEWCONFIG_USAGE = "UPDATE_NEWCONFIG_USAGE";
export const NEWCONFIG_VALIDATION_PASSED = "NEWCONFIG_VALIDATION_PASSED";
export const NEWCONFIG_VALIDATION_FAILED = "NEWCONFIG_VALIDATION_FAILED";
export const SUBMIT_NEWCONFIG = "SUBMIT_NEWCONFIG";
export const NEWCONFIG_CREATED = "NEWCONFIG_CREATED";
export const SUBMIT_NEWCONFIG_FAILED = "SUBMIT_NEWCONFIG_FAILED";

export const OPEN_DUPLCONFIG_MODAL = "OPEN_DUPLCONFIG_MODAL";
export const CLOSE_DUPLCONFIG_MODAL = "CLOSE_DUPLCONFIG_MODAL";
export const UPDATE_DUPLCONFIG_RECEIVERID = "UPDATE_DUPLCONFIG_RECEIVERID";
export const UPDATE_DUPLCONFIG_PURPOSE = "UPDATE_DUPLCONFIG_PURPOSE";
export const UPDATE_DUPLCONFIG_USAGE = "UPDATE_DUPLCONFIG_USAGE";
export const DUPLCONFIG_VALIDATION_PASSED = "DUPLCONFIG_VALIDATION_PASSED";
export const DUPLCONFIG_VALIDATION_FAILED = "DUPLCONFIG_VALIDATION_FAILED";
export const SUBMIT_DUPLCONFIG = "SUBMIT_DUPLCONFIG";
export const DUPLCONFIG_CREATED = "DUPLCONFIG_CREATED";
export const SUBMIT_DUPLCONFIG_FAILED = "SUBMIT_DUPLCONFIG_FAILED";

export const SUBMIT_DELETE_CONFIG = "SUBMIT_DELETE_CONFIG";
export const CONFIG_DELETED = "CONFIG_DELETED";
export const DELETE_CONFIG_FAILED = "DELETE_CONFIG_FAILED";

export const REQUEST_SITE_LOG = "REQUEST_SITE_LOG";
export const REQUEST_SITE_LOG_FAIL = "REQUEST_SITE_LOG_FAIL";
export const RECEIVED_SITE_LOG = "RECEIVED_SITE_LOG";

export const REQUEST_SITE_TEMPLATES = "REQUEST_SITE_TEMPLATES";
export const REQUEST_SITE_TEMPLATES_FAIL = "REQUEST_SITE_TEMPLATES_FAIL";
export const RECEIVED_SITE_TEMPLATES = "RECEIVED_SITE_TEMPLATES";

export const REQUEST_SITE_TEMPLATE = "REQUEST_SITE_TEMPLATE";
export const REQUEST_SITE_TEMPLATE_FAIL = "REQUEST_SITE_TEMPLATE_FAIL";
export const RECEIVED_SITE_TEMPLATE = "RECEIVED_SITE_TEMPLATE";

export const SELECT_SITE_TEMPLATE = "SELECT_SITE_TEMPLATE";
export const DESELECT_SITE_TEMPLATE = "DESELECT_SITE_TEMPLATE";
export const DESELECT_SITE_ASTEMPLATE = "DESELECT_SITE_ASTEMPLATE";

export const REQUEST_FORM_CONFIG = "REQUEST_FORM_CONFIG";
export const RECEIVED_FORM_CONFIG = "RECEIVED_FORM_CONFIG";
export const REQUEST_FORM_CONFIG_FAIL = "REQUEST_FORM_CONFIG_FAIL";

export const REQUEST_SITE_PROFILE = "REQUEST_SITE_PROFILE";
export const RECEIVED_SITE_PROFILE = "RECEIVED_SITE_PROFILE";
export const REQUEST_SITE_PROFILE_FAIL = "REQUEST_SITE_PROFILE_FAIL";

export const OPEN_GPARAM_MODAL = "OPEN_GPARAM_MODAL";
export const CLOSE_GPARAM_MODAL = "CLOSE_GPARAM_MODAL";

export const SELECT_GPARAM = "SELECT_GPARAM";
export const DESELECT_GPARAM = "DESELECT_GPARAM";

export const SHOW_NEWGPARAM_FORM = "SHOW_NEWGPARAM_FORM";
export const HIDE_NEWGPARAM_FORM = "HIDE_NEWGPARAM_FORM";

export const SHOW_EDITGPARAM_MODAL = "SHOW_EDITGPARAM_MODAL";
export const HIDE_EDITGPARAM_MODAL = "HIDE_EDITGPARAM_MODAL";

export const SHOW_DELETE_GPARAM_CONFIRMATION =
  "SHOW_DELETE_GPARAM_CONFIRMATION";
export const HIDE_DELETE_GPARAM_CONFIRMATION =
  "HIDE_DELETE_GPARAM_CONFIRMATION";

export const REQUEST_GPARAMS = "REQUEST_GPARAMS";
export const RECEIVED_GPARAMS = "RECEIVED_GPARAMS";
export const REQUEST_GPARAMS_FAIL = "REQUEST_GPARAMS_FAIL";

export const REQUEST_GPARAMS_CATEGORY = "REQUEST_GPARAMS_CATEGORY";
export const RECEIVED_GPARAMS_CATEGORY = "RECEIVED_GPARAMS_CATEGORY";
export const REQUEST_GPARAMS_CATEGORY_FAIL = "REQUEST_GPARAMS_CATEGORY_FAIL";

export const REQUEST_GPARAMS_GROUP = "REQUEST_GPARAMS_GROUP";
export const RECEIVED_GPARAMS_GROUP = "RECEIVED_GPARAMS_GROUP";
export const REQUEST_GPARAMS_GROUP_FAIL = "REQUEST_GPARAMS_GROUP_FAIL";

export const REQUEST_FILTERED_GPARAMS = "REQUEST_FILTERED_GPARAMS";
export const RECEIVED_FILTERED_GPARAMS = "RECEIVED_FILTERED_GPARAMS";
export const REQUEST_FILTERED_GPARAMS_FAIL = "REQUEST_FILTERED_GPARAMS_FAIL";

export const TURN_ON_PRINTMAILSERVICE = "TURN_ON_PRINTMAILSERVICE";
export const TURN_OFF_PRINTMAILSERVICE = "TURN_OFF_PRINTMAILSERVICE";

export const REQUEST_ACTIVESITE_JOBS = "REQUEST_ACTIVESITE_JOBS";
export const RECEIVED_ACTIVESITE_JOBS = "RECEIVED_ACTIVESITE_JOBS";
export const REQUEST_ACTIVESITE_JOBS_FAIL = "REQUEST_ACTIVESITE_JOBS_FAIL";

export const REQUEST_SITE_JOBS = "REQUEST_SITE_JOBS";
export const RECEIVED_SITE_JOBS = "RECEIVED_SITE_JOBS";
export const REQUEST_SITE_JOBS_FAIL = "REQUEST_SITE_JOBS_FAIL";

export const REQUEST_DEFAULT_FTP_JOBS = "REQUEST_DEFAULT_FTP_JOBS";
export const RECEIVED_DEFAULT_FTP_JOBS = "RECEIVED_DEFAULT_FTP_JOBS";
export const REQUEST_DEFAULT_FTP_JOBS_FAIL = "REQUEST_DEFAULT_FTP_JOBS_FAIL";

export const REQUEST_DEFAULT_FTP_CONFIG = "REQUEST_DEFAULT_FTP_CONFIG";
export const RECEIVED_DEFAULT_FTP_CONFIG = "RECEIVED_DEFAULT_FTP_CONFIG";
export const REQUEST_DEFAULT_FTP_CONFIG_FAIL =
  "REQUEST_DEFAULT_FTP_CONFIG_FAIL";

export const REQUEST_ACTIVESITE_INBOUND_FILES =
  "REQUEST_ACTIVESITE_INBOUND_FILES";
export const RECEIVED_ACTIVESITE_INBOUND_FILES =
  "RECEIVED_ACTIVESITE_INBOUND_FILES";
export const REQUEST_ACTIVESITE_INBOUND_FILES_FAIL =
  "REQUEST_ACTIVESITE_INBOUND_FILES_FAIL";

export const REQUEST_DEFAULT_FTP_NOTIFY = "REQUEST_DEFAULT_FTP_NOTIFY";
export const RECEIVED_DEFAULT_FTP_NOTIFY = "RECEIVED_DEFAULT_FTP_NOTIFY";
export const REQUEST_DEFAULT_FTP_NOTIFY_FAIL =
  "REQUEST_DEFAULT_FTP_NOTIFY_FAIL";
